package com.mjbmjb.cf.taskmaster.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.UUID;

@DynamoDBTable(tableName = "taskmaster")
public class TaskMaster {

    private UUID id;
    private String title;
    private String description;
    private String status;
    private String[] statusState = new String[]{"Available", "Assigned", "Accepted", "Finished"};
    private int statusTracker;

    public TaskMaster(){}

    public TaskMaster(String title, String description){
        this.title = title;
        this.description = description;
        this.statusTracker = 0;
        this. status = statusState[this.statusTracker];

    }

    //getters
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @DynamoDBTyped
    public UUID getId() {
        return this.id;
    }

    @DynamoDBAttribute(attributeName = "title")
    @DynamoDBTyped
    public String getTitle() {
        return this.title;
    }

    @DynamoDBAttribute(attributeName = "description")
    @DynamoDBTyped
    public String getDescription() {
        return this.description;
    }

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTyped
    public String getStatus() {
        return this.status;
    }

    @DynamoDBAttribute(attributeName = "statusState")
    @DynamoDBTyped
    public String[] getStatusState() {
        return this.statusState;
    }

    @DynamoDBAttribute(attributeName = "statusTracker")
    @DynamoDBTyped
    public int getStatusTracker() {
        return this.statusTracker;
    }

    //setters
    public void setId(UUID id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setStatusTracker(int value) {
        this.statusTracker = value;
    }

}
