package com.mjbmjb.cf.taskmaster.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "Task")
public class Task {

    private UUID id;
    private String title;
    private String description;
    private String status;
    private String[] statusState = new String[]{"Available", "Assigned", "Accepted", "Finished"};

    public Task(){}

    public Task(String title, String description, String status){
        this.title = title;
        this.description = description;
        this. status = status;
    }

    //getters
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return this.id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return this.description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return this.status;
    }

    //setters
    public void setId(UUID id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
