package com.mjbmjb.cf.taskmaster.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@DynamoDBTable(tableName = "taskmaster")
public class TaskMaster {

    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private int statusTracker;
//    private List<String> availableStatus = new ArrayList<>(Arrays.asList("Available", "Assigned", "Accepted", "Finished"));



    public TaskMaster(){}

    public TaskMaster(String title, String description, String assignee){
        this.title = title;
        this.description = description;
        this.assignee = assignee;
//        if(assignee == null) {
//            this.statusTracker = 0;
//        } else {
//            this.statusTracker = 1;
//        }
//        this.status = this.availableStatus.get(this.statusTracker);
    }

    //getters
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return this.description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return this.status;
    }

    @DynamoDBAttribute
    public int getStatusTracker() {
        return this.statusTracker;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return this.assignee;
    }
//
//    @DynamoDBAttribute
//    public List<String> getAvailableStatus() {
//        return this.availableStatus;
//    }

    //setters
    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setStatusTracker(int statusTracker) {
        this.statusTracker = statusTracker;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }
}
